---
title: "Vijay Data"
author: "Alex Greenshields Watson"
date: "26/11/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r import data, include=T, echo=T, message=FALSE, warning=FALSE, results='asis', fig.height=6, fig.width=24}


setwd("~/Dropbox/POSTDOC/Paper-CD4Flu/data_vijay")
#setwd("C:/Users/Green/Dropbox/POSTDOC/Paper-CD4Flu/data_vijay")


library(readxl)
library(magrittr)
library(stringi)
library(tidyverse)

raw_data_vijay <- read_xlsx("Epitope_flu_1_.xlsx", col_names = F)

test_regex <- map_dfc(.x = raw_data_vijay,
                      .f = function(x) sub(pattern = "\\d*% ", replacement = "", x)) %>%
  map_dfc( .f = function(x) sub(pattern = "0.%", replacement = "", x)) %>%
  map_dfc( .f = function(x) sub(pattern = "\\d*%", replacement = "", x)) %>%
  map_dfc( .f = function(x) sub(pattern = "\\(", replacement = "", x)) %>% 
  map_dfc( .f = function(x) sub(pattern = "\\)", replacement = "", x))

human_df <- test_regex[ -c(1:2, 11:14, 23:26, 35:38, 49:52, 63:68) , 1:10] %>% 
  set_colnames( c("Neuraminidase", test_regex[2, 2:10] )) %>% as_tibble() %>%
  add_column("Epitope"= c(map(.x=c( "SGP",  "GLI",  "QAR"), .f = function(x) rep(x, 8)) %>% unlist(),
                          map(.x=c( "DPF",  "GMF"), .f = function(x) rep(x, 10)) %>% unlist()), 
             .after = 1  )

human_df[20,7] <- "2/3"
human_df[10,11] <- "5/5"

swine_df <- test_regex[ -c(1:2, 10:13, 21:24, 32:35, 43:46, 56:68) , 12:22]  %>% 
  set_colnames( c("Neuraminidase", test_regex[2, 13:22] )) %>% as_tibble() %>%
  add_column("Epitope"= c(map(.x=c( "SGP",  "GLI",  "QAR", "DPF"), .f = function(x) rep(x, 7)) %>% unlist(),
                          map(.x=c( "GMF"), .f = function(x) rep(x, 9)) %>% unlist()), 
             .after = 1  )

swine_df[12,12] <- "0/1"

avian_df <- test_regex[ -c(1:2, 13:16, 27:30, 42:45, 55:58), 25:42] %>% 
  set_colnames( c("Neuraminidase", test_regex[2, 26:42] )) %>% as_tibble()%>%
  add_column("Epitope"= c(map(.x=c( "SGP",  "GLI"), .f = function(x) rep(x, 10)) %>% unlist(),
                          map(.x=c( "QAR"), .f = function(x) rep(x, 11)) %>% unlist(),
                          map(.x=c( "DPF"), .f = function(x) rep(x, 9)) %>% unlist(), 
                          map(.x=c( "GMF"), .f = function(x) rep(x, 10)) %>% unlist()), 
             .after = 1  )

avian_df[37, 9] <- "27/48"
avian_df[50, 1] <- "unknown"

quantify_fxn <- function(df){ 
  df[, 3:ncol(df)] <-  map_dfc(df[ , 3:ncol(df)],  
                               function(x){ 
                                 map_dbl(x, possibly(.f= function(y) eval(parse(text = y)), otherwise = "Missing")
                                 ) } )
  
  return(df)
}

# make a bar chart



bar_chart <- tribble(~x, ~y,
                     1, 1:2,
                     13, 1:2,
                     25, 1:2,
                     37, 1:2,
                     51, 1:2,
                     1, 12:13,
                     12, 12:13,
                     23, 12:13,
                     34, 12:13,
                     45, 12:13,
                     1, 25:26,
                     15, 25:26,
                     29, 25:26,
                     44, 25:26,
                     57, 25:26,)

bar_data <- NULL

pmap(bar_chart, function(x,y){
  df <- bind_rows(bar_data, test_regex[x, y]%>%set_colnames(c("Epitope", "Numbers")))
  assign("bar_data", df, envir = .GlobalEnv)
})

library(forcats)
library(ggpubr)

bar_data %>% separate(Epitope, into = c("Species", "Protein"), sep = "_") %>% 
  add_column("Epitope"=rep(c("SGP", "GLI", "QAR", "DPF", "GMF"), 3) %>% factor(c("SGP", "GLI", "QAR", "DPF", "GMF"))) %>%
  mutate(Species=sub("#", "", Species)) %>%
  separate(Numbers, into = c("Conserved", "Total"), sep = "/") %>%
  mutate(Conserved=as.numeric(Conserved)) %>%
  mutate(Total=as.numeric(Total)) %>%
  mutate(Protein=rep(c("M1", "M1", "M1", "NP", "PB1"), 3))-> bar_data

bar_data <- bar_data %>% mutate("Percentage"=Conserved/Total)

bar_data %>% gather(Conserved, Total, key = "Sequences", value = "Number") %>% 
  ggplot(aes(x = Epitope, y = Number, fill=Sequences)) +
  geom_col(position = "dodge") +
  theme_pubr() +
  scale_fill_manual(values = c("dodgerblue", "black"))+
  theme(text = element_text(size = 12), legend.position = "right",
        legend.title = element_blank(),
        axis.text.x = element_text(angle = -45, vjust = 0, hjust = 0.5)) +
  facet_wrap(~Species, scales = "free") +
  xlab(element_blank()) + ylab("Sequence Count") +
  ggsave(filename = "Sequence_bar_chart.png", device = "png",
         height = 6, width = 24, units = "cm")

```


```{r heat maps data, include=T, echo=T, message=FALSE, warning=FALSE, results='asis', fig.height=10, fig.width=4}

# Heat Maps

avian_df_quant <- quantify_fxn(avian_df) %>% 
  filter(Neuraminidase!="unknown") %>% select(-c("UNKNOWN")) %>%
  # unite("Rowname", Neuraminidase, Epitope,  sep = " ") %>% {
  #   chr <- (.) %>% pull(Rowname)
  #   as.matrix( (.)[, -1]) %>% `row.names<-`(chr)    }
  select(-Epitope) %>%  {
    chr <- (.) %>% pull(Neuraminidase)
    as.matrix( (.)[, -1]) %>% `row.names<-`(chr)    }


human_df_quant <- quantify_fxn(human_df) %>% 
  filter(Neuraminidase!="unknown") %>% select(-c("unknown")) %>%
  # unite("Rowname", Neuraminidase, Epitope,  sep = " ") %>% {
  #   chr <- (.) %>% pull(Rowname)
  #   as.matrix( (.)[, -1]) %>% `row.names<-`(chr)    }
  select(-Epitope) %>%  {
    chr <- (.) %>% pull(Neuraminidase)
    as.matrix( (.)[, -1]) %>% `row.names<-`(chr)    }

swine_df_quant <- quantify_fxn(swine_df) %>% 
  filter(Neuraminidase!="unknown") %>% 
  # unite("Rowname", Neuraminidase, Epitope,  sep = " ") %>% {
  #   chr <- (.) %>% pull(Rowname)
  #   as.matrix( (.)[, -1]) %>% `row.names<-`(chr)    }
  select(-Epitope) %>%  {
    chr <- (.) %>% pull(Neuraminidase)
    as.matrix( (.)[, -1]) %>% `row.names<-`(chr)    }


# Make some heatmaps_df_quant,
library(pheatmap)

pheatmap(avian_df_quant,
         cluster_rows = F,
         cluster_cols= F,
         gaps_row = c(9,18,28,37),
         color = colorRampPalette(c("black", "dodgerblue"))(50),
         #main = "Avian",
         fontsize = 16,
         #filename = "avian_conservation.png",
         #height = 10, width = 4.5, 
         border_color = "black",
         silent = F,
         legend = F
)

pheatmap(human_df_quant,
         cluster_rows = F,
         cluster_cols= F,
         gaps_row = c(7,14,21,30),
         color = colorRampPalette(c("black", "dodgerblue"))(50),
         #main = "Human",
         fontsize = 16,
         #filename = "human_conservation.png",
         #height = 10, width = 3.5, 
         border_color = "black",
         silent = F,
         legend = F)

pheatmap(swine_df_quant,
         cluster_rows = F,
         cluster_cols= F,
         gaps_row = c(7,14,21,28),
         color = colorRampPalette(c("black", "dodgerblue"))(50),
         #main = "Swine",
         fontsize = 16,
         #filename = "swine_conservation.png",
         #height = 10, width = 3.8, 
         border_color = "black",
         silent = F,
         legend = T)


```