---
title: "B-Factor_Analysis_2020"
author: "Alex Greenshields Watson"
date: "24/02/2020"
output: pdf_document
---

```{r setup, include=T, echo=T, message=FALSE, warning=FALSE, results='asis'}

#install.packages("bio3d")

library(bio3d)
library(magrittr)
library(purrr)
library(tibble)
library(dplyr)
library(ggplot2)
library(ggpubr)

# B-factor calculator

setwd("~/01_Crystal_data_figures/final_str_files/bin/")

complex <- read.pdb2("../coordinates/pky.pdb")
gmf <- read.pdb2("../coordinates/gmf.pdb")
qar <- read.pdb2("../coordinates/qar.pdb")
sgp <- read.pdb2("../coordinates/sgp.pdb")

```


```{r isolate b factors, include=T, echo=T, message=FALSE, warning=FALSE, results='asis'}

# get bfactors

# Peptides
B_factors <- tribble(~Peptide, ~`B-Factor`, ~Residues, ~Eleno, ~Residue_no, ~Core, ~Atom,
                     
                     "PKY", 
                     complex$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(b) ,
                     complex$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resid) %>% unlist(),
                     complex$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(eleno),
                     complex$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resno)  %>% map_dbl( .f = function(x){x-(min((.))-1)}),
                     complex$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resno)  %>% map_dbl( .f = function(x){x-(min((.))-1)}) %>%
                       as.character() %>% {case_when( ( (.) %in% c("1", "2", "12", "13") ) ~ "Flanks", 
                                                      !(  (.) %in% c("1", "2", "12", "13") ) ~ "Core")},
                     complex$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(elety),
                     
                     
                     "GMF", 
                     gmf$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(b),
                     gmf$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resid) %>% unlist(),
                     gmf$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(eleno),
                     gmf$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resno) %>% map_dbl( .f = function(x){x-(min((.))-1)}),
                     gmf$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resno)  %>% map_dbl( .f = function(x){x-(min((.))-1)}) %>%
                       as.character() %>% {case_when( ( (.) %in% as.character(c(1:3, 13:17)) ) ~ "Flanks", 
                                                      !(  (.) %in% as.character(c(1:3, 13:17)) ) ~ "Core")},
                     gmf$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(elety),
                     
                     "SGP",  
                     sgp$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(b) ,
                     sgp$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resid) %>% unlist(),
                     sgp$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(eleno),
                     sgp$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resno) %>% map_dbl( .f = function(x){x-(min((.))-1)}),
                     sgp$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resno)  %>% map_dbl( .f = function(x){x-(min((.))-1)}) %>%
                       as.character() %>% {case_when( ( (.) %in% c("1", "2", "3", "13", "14") ) ~ "Flanks", 
                                                      !(  (.) %in% c("1", "2", "3", "13", "14") ) ~ "Core")},
                     sgp$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(elety),
                     
                     "QAR",  
                     qar$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(b) ,
                     qar$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resid) %>% unlist(),
                     qar$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(eleno),
                     qar$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resno) %>% map_dbl( .f = function(x){x-(min((.))-1)}),
                     qar$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(resno)  %>% map_dbl( .f = function(x){x-(min((.))-1)}) %>%
                       as.character() %>% {case_when( ( (.) %in% as.character(c(1:5, 15, 16)) ) ~ "Flanks", 
                                                      !(  (.) %in% as.character(c(1:5, 15, 16)) ) ~ "Core")},
                     qar$atom %>% as_tibble() %>% filter(chain=="C") %>% pull(elety)
                     
                     
)


```

```{r plots, include=T, echo=T, message=FALSE, warning=FALSE, results='asis', fig.height=5, fig.width=10}


# make a new tibble 
plot_df <- tribble(~Peptide, ~Bfactor, ~eleno, ~Residue, ~Core, ~Atom)

walk(.x = c(1:4), .f = function(i){
  
  df <- bind_rows(plot_df, tibble("Peptide"=B_factors$Peptide[[i]], 
                                  "Bfactor"=B_factors$`B-Factor`[i] %>% unlist,
                                  "eleno"=B_factors$Eleno[i] %>% unlist,
                                  "Residue"=B_factors$Residue_no[i] %>% unlist,
                                  "Core"=B_factors$Core[i] %>% unlist,
                                  "Atom"=B_factors$Atom[i] %>% unlist )
  )
  
  assign("plot_df", value = df, envir = .GlobalEnv)
  
}
)

plot_df <- plot_df %>% add_column("n"= 1:nrow(plot_df))

breaking <- c(plot_df %>% filter(Peptide=="GMF") %>% .[!duplicated( .$Residue ), "n" ] %>% pull(n),
              plot_df %>% filter(Peptide=="PKY") %>% .[!duplicated( .$Residue ), "n" ] %>% pull(n),
              plot_df %>% filter(Peptide=="QAR") %>% .[!duplicated( .$Residue ), "n" ] %>% pull(n),
              plot_df %>% filter(Peptide=="SGP") %>% .[!duplicated( .$Residue ), "n" ] %>% pull(n))

b_factor_fxn <- function(peptide) {
  
  pep <- peptide
  plen <- plot_df %>% filter(Peptide==pep) %>% nrow()
  
  plot_df %>% filter(Peptide==pep) %>%
    ggplot(  aes(x=n, y=Bfactor, fill = Core)  ) +
    geom_bar(color="black", stat = "identity", size = 0.4) +
    xlab(NULL) + 
    ylab("Atomic B-Factor") +
    theme_pubr() + 
    theme(legend.position = "none",
          axis.ticks.length.x = unit(0.5, "cm"),
          text = element_text(size = 20),
          panel.grid.major.x = element_line(colour = "gray80", size = 0.4),
          panel.grid.major.y = element_line(colour = "gray80", size = 0.4),
          panel.border = element_rect(colour = "black", size = 1.0, fill = NA),
          axis.ticks = element_line(colour = "black", size = 0.4)
    ) +
    
    scale_x_continuous(breaks = breaking-0.5, labels = NULL, expand = c( 0, 0))  +
    
    scale_y_continuous(breaks = c( (1:10)*50), limits = c( 0, 155), 
                       expand = c( 0, 0))  +
    
    ggsave(filename = paste0("../output/bfactors/bfactors", pep, ".png"),
           plot = last_plot(),
           dpi = 300,
           width = plen/15,
           height = 4) }

pep_list <- list("GMF", "PKY", "QAR", "SGP")

walk(pep_list, b_factor_fxn )

# make some ggplots - like in Bruce's paper.

plot_df <- plot_df %>% mutate(Bfactor = case_when(
  Atom=="N" |Atom=="CA"| Atom=="C"| Atom=="O" ~ Bfactor*-1,
  !(Atom=="N" |Atom=="CA"| Atom=="C"| Atom=="O") ~ Bfactor*1)
  )

double_b_factor_fxn <- function(peptide) {
  
  pep <- peptide
  plen <- plot_df %>% filter(Peptide==pep) %>% nrow()
  
  plot_df %>% filter(Peptide==pep) %>%
    ggplot(  aes(x=n, y=Bfactor, fill = Core)  ) +
    geom_bar(color="black", stat = "identity", size = 0.4) +
    xlab(NULL) + 
    ylab("Atomic B-Factor") +
    theme_pubr() + 
    theme(legend.position = "none",
          axis.ticks.length.x = unit(0.5, "cm"),
          text = element_text(size = 20),
          panel.grid.major.x = element_line(colour = "gray80", size = 0.4),
          panel.grid.major.y = element_line(colour = "gray80", size = 0.4),
          panel.border = element_rect(colour = "black", size = 1.0, fill = NA),
          axis.ticks = element_line(colour = "black", size = 0.4)
    ) +
    
    scale_x_continuous(breaks = breaking-0.5, labels = NULL, expand = c( 0, 0))  +
    
    scale_y_continuous(breaks = c(-150, -100, -50, (1:10)*50), limits = c( -155, 155), 
                       expand = c( 0, 0))  +
    
    ggsave(filename = paste0("../output/bfactors/double_bfactors", pep, ".png"),
           plot = last_plot(),
           dpi = 300,
           width = plen/15,
           height = 4) }

pep_list <- list("GMF", "PKY", "QAR", "SGP")

walk(pep_list, double_b_factor_fxn )

```




